"""add bank accounts and recurrences

Revision ID: 436df50938d6
Revises: 
Create Date: 2026-03-08 17:45:35.698998

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '436df50938d6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('families', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_families_invite_token'), ['invite_token'])

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('account_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_transactions_account_id_bank_accounts'), 'bank_accounts', ['account_id'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_users_email'), ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_users_email'), type_='unique')

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_transactions_account_id_bank_accounts'), type_='foreignkey')
        batch_op.drop_column('account_id')

    with op.batch_alter_table('families', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_families_invite_token'), type_='unique')

    # ### end Alembic commands ###
